"""Committee orchestrator: 2-round debate + majority vote."""

import json
import logging
from collections import Counter
from datetime import datetime

import pytz

from app.core.proposal import TradeProposalCreateRequest
from app.decision.agents import ClaudeAgent, GPT4oAgent, GrokAgent
from app.decision.models import AgentVote, CommitteeRun
from app.marketdata.indicators import compute_indicators
from app.storage.database import (
    create_trade_proposal,
    get_active_watchlist_symbols,
    get_agent_config,
    get_latest_news,
    get_market_closes,
    save_committee_run,
)

logger = logging.getLogger(__name__)

PARIS_TZ = pytz.timezone("Europe/Paris")


def _build_market_context(symbols: list[str]) -> str:
    lines: list[str] = []
    for symbol in symbols:
        closes = get_market_closes(symbol, timeframe="1d", limit=50)
        if not closes:
            lines.append(f"  {symbol}: no data")
            continue
        indicators = compute_indicators(symbol, closes)
        trend = "bullish" if (indicators.sma20 or 0) > (indicators.sma50 or 0) else "bearish"
        rsi = f"{indicators.rsi14:.1f}" if indicators.rsi14 else "N/A"
        vol = f"{indicators.volatility:.4f}" if indicators.volatility else "N/A"
        lines.append(
            f"  {symbol}: last_close={closes[-1]:.2f}  RSI14={rsi}  trend={trend}  volatility={vol}"
        )
    return "\n".join(lines) if lines else "  (no symbols in watchlist)"


def _majority_vote(votes: list[AgentVote]) -> tuple[str, str, float | None]:
    """Return (action, ticker, notional_eur) of the majority or HOLD on tie.

    Active agents = those with a non-empty ticker (keys not set → ticker="").
    Majority threshold: >50% of active agents. With only 1 active agent, that
    agent's vote wins automatically.
    """
    active = [v for v in votes if v.ticker]
    if not active:
        return "HOLD", "", None

    threshold = max(1, len(active) // 2 + 1)  # strict majority of active agents

    counter: Counter[tuple[str, str]] = Counter((v.action, v.ticker) for v in active)
    (action, ticker), count = counter.most_common(1)[0]

    if count < threshold:
        return "HOLD", ticker, None

    matching = [v for v in active if v.action == action and v.ticker == ticker]
    notionals = [v.notional_eur for v in matching if v.notional_eur]
    avg_notional = sum(notionals) / len(notionals) if notionals else None

    return action, ticker, avg_notional


def run_committee() -> CommitteeRun:
    """Run one full committee session: 2 rounds + vote → PENDING proposal."""
    paris_now = datetime.now(PARIS_TZ)
    paris_time_str = paris_now.strftime("%Y-%m-%d %H:%M %Z")

    symbols = get_active_watchlist_symbols()
    market_context = _build_market_context(symbols)
    news_items = get_latest_news(limit=5)
    news_headlines = "\n".join(f"  - {item.title}" for item in news_items) or "  (no recent news)"

    cfg = get_agent_config()
    agents = []
    if cfg.claude_enabled:
        agents.append(ClaudeAgent())
    if cfg.gpt4o_enabled:
        agents.append(GPT4oAgent())
    if cfg.grok_enabled:
        agents.append(GrokAgent())
    if not agents:
        agents = [ClaudeAgent()]  # fallback: always keep at least one agent

    # ── Round 1: independent analysis ────────────────────────────────────────
    logger.info("Committee round 1 starting")
    round1: list[AgentVote] = [
        agent.initial_vote(market_context, news_headlines, paris_time_str) for agent in agents
    ]

    # ── Round 2: debate (each agent sees the other two's round-1 votes) ───────
    logger.info("Committee round 2 (debate) starting")
    round2: list[AgentVote] = []
    for i, agent in enumerate(agents):
        peers = [v for j, v in enumerate(round1) if j != i]
        revised = agent.debate_vote(round1[i], peers)
        round2.append(revised)

    # ── Vote ──────────────────────────────────────────────────────────────────
    action, ticker, notional_eur = _majority_vote(round2)
    logger.info("Committee decision: %s %s notional=%s", action, ticker, notional_eur)

    # ── Create proposal in DB ─────────────────────────────────────────────────
    proposal_id: int | None = None
    if action in ("BUY", "SELL") and ticker:
        thesis = {
            "source": "committee",
            "round1": [v.model_dump() for v in round1],
            "round2": [v.model_dump() for v in round2],
        }
        market = "US" if not ticker.endswith(".PA") else "EU"
        proposal = create_trade_proposal(
            TradeProposalCreateRequest(
                symbol=ticker,
                asset_type="EQUITY",
                market=market,
                side=action,  # type: ignore[arg-type]
                order_type="LIMIT",
                notional_eur=notional_eur,
                horizon_window="jours/semaines",
                thesis_json=json.dumps(thesis),
                notes="Generated by AI committee",
                status="PENDING",
            )
        )
        proposal_id = proposal.id

    run = save_committee_run(
        run_at=paris_now.isoformat(),
        votes_round1=round1,
        votes_round2=round2,
        winning_action=action,  # type: ignore[arg-type]
        winning_ticker=ticker,
        winning_notional_eur=notional_eur,
        proposal_id=proposal_id,
        error=None,
    )
    return run


def is_market_open() -> bool:
    """True if current Paris time is within US market hours Mon-Fri 15:30-22:00."""
    now = datetime.now(PARIS_TZ)
    if now.weekday() >= 5:  # Saturday=5, Sunday=6
        return False
    open_time = now.replace(hour=15, minute=30, second=0, microsecond=0)
    close_time = now.replace(hour=22, minute=0, second=0, microsecond=0)
    return open_time <= now <= close_time
